config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'  
  get    '/about',     to: 'static_pages#about'
  get    '/contact',   to: 'static_pages#contact'
  get    '/signup',    to: 'users#new'
  get    '/login',     to: 'sessions#new'
  post   'login',      to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  resources :users

  mount GitHooks::Engine, at: "/git_hooks"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = self.email.downcase }
  validates( :name, presence: true, length: { maximum:  50 })
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates(:email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false })

  has_secure_password
  validates(:password, presence: true, length: { minimum: 6 }, allow_nil: true)

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
   before_action :set_user,       only: [:show, :edit, :update]
   before_action :correct_user,   only: [:edit, :update]
   before_action :admin_user,     only: :destroy
 

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = "You have successfully created an account!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash.now[:success] = "Profile successfully updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

      def user_params
        params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation, :about)
      end  

      def logged_in_user
        unless logged_in?
          flash[:danger] = "You have to log in before you can do that action."
          redirect_to login_url
        end
      end 

      def correct_user
        redirect_to root_url unless @user == current_user
      end

      def set_user
        @user = User.find(params[:id])
      end

      def admin_user
        redirect_to root_url unless current_user.admin?
      end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Sycamore Education"
    if page_title.empty?
      base_title
    else 
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created by <a href="https://www.michaelschneider.me/"> Michael Schneider </a>
    as part of a project during my summer with 
    <a href="https://sycamoreeducation.com">Sycamore</a>.
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Sycamore", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag asset_path('sycamore_leaf_red.jpg') %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %> 
    </ul>
  </div>
<% end %> 

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1> About </h1>
<p> 
  This is a page I have created to demonstrate what should go on an About page. 
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1> Contact </h1>
<p> 
  This is a page where I would put my contact information, hypothetically speaking. 
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1 style="font-size: 3.2em">Sycamore Education</h1>

  <h2>
    My name is <a href="https://www.michaelschneider.me/"> Michael </a>. I'm working with
    <a href="https://sycamoreeducation.com">Sycamore Education</a>
    this summer and I'm creating this sammple app with Rails to try some things out. 
  </h2>
  
  <h2> 
    The website isnt set up in a way where signing up does anything worthwhile,
    but you can still sign up and make a profile to edit your personal information
    to see that it works! 
  </h2>
  
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %> </br></br>

<%= link_to image_tag("sycamore_leaf.jpg", height: '40', width: '40', alt: "Sycamore Leaf"),
            'http://sycamoreeducation.com/' %>

<%= ENV["GITHUB_TOKEN"] %>

</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, data: { confirm: "This cannot be undone. Are you sure?" } %>
  <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, "Save these personal info changes") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= render "form" %>
  </br>
  <hr>
  <h1>Update your Bio</h1>

  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label "Change my 'About me' page" %>
    <%= f.text_area :about, as: :text, class: 'form-control', :rows => '6' %>
    <%= f.submit "Save my new bio", class: 'btn btn-primary' %>
  <% end %>
  </br>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel='noopener'>Change Gravatar</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1> User Directory </h1>
<ul class="users">
<%= will_paginate %>
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
<%= will_paginate %>
</ul>



app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, "Create My Account") %>
<h1 style = 'padding-top: 40px'>Sign up</h1>
<div class="row">
  <div class = "col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<% provide(:button_text, "Edit my Bio")%>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1 style='padding-bottom: 10px; text-align: center; font-weight: bold;'>
        <%= gravatar_for @user %>
        </br>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  
  <h1> About Me </h1>
  <%= @user.about %>
   
  
  
</div> 